# Generated by Django 5.1.3 on 2024-11-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_category_slug_remove_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='is_available',
        ),
    ]
