# Generated by Django 5.1.3 on 2024-11-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_slug_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
