# Generated by Django 5.1.3 on 2024-11-10 22:55

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=12, prefix='', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=20, prefix='TR', primary_key=True, serialize=False, unique=True),
        ),
    ]
