# Generated by Django 5.1.3 on 2024-11-11 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_rate',
        ),
    ]
