# Generated by Django 5.1.3 on 2024-11-13 11:26

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_shipping_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=10, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
